# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc0745e1e54221b61ba5118815479d7b2675941ef3a4b87e1f7994cecabe07665a7ac66addc239a69709ca7ec12943d287ee774cf0ffd303b2d5311ede7452a2

test:
  secret_key_base: 0c8aa58c4f66fee0a71346adbc74d1176da557e049e857981e450668c3253884fa3900f38825219dc8153761ccfd4171a2d45f88d5a0b09e636b9ce2fc193836

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
